export const GET_LIST_CATEGORIES = 'home/GET_LIST_CATEGORIES';
export const GET_LIST_CATEGORIES_SUCCESS = 'home/GET_LIST_CATEGORIES_SUCCESS';
export const GET_LIST_CATEGORIES_FAILURE = 'home/GET_LIST_CATEGORIES_FAILURE';
