export const GET_LIST_QUESTIONS = 'question/GET_LIST_QUESTIONS';
export const GET_LIST_QUESTIONS_SUCCESS = 'question/GET_LIST_QUESTIONS_SUCCESS';
export const GET_LIST_QUESTIONS_FAILURE = 'question/GET_LIST_QUESTIONS_FAILURE';
export const ANSWER_QUESTION = 'question/ANSWER_QUESTION';
export const SUBMIT_QUESTION = 'question/SUBMIT_QUESTION';
