export const GET_LIST_TOPICS = 'topic/GET_LIST_TOPICS';
export const GET_LIST_TOPICS_SUCCESS = 'topic/GET_LIST_TOPICS_SUCCESS';
export const GET_LIST_TOPICS_FAILURE = 'topic/GET_LIST_TOPICS_FAILURE';
